# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(412, 414)
        self.login = QtWidgets.QPushButton(parent=Dialog)
        self.login.setGeometry(QtCore.QRect(60, 290, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.login.setFont(font)
        self.login.setObjectName("login")
        self.register_2 = QtWidgets.QPushButton(parent=Dialog)
        self.register_2.setGeometry(QtCore.QRect(250, 290, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.register_2.setFont(font)
        self.register_2.setObjectName("register_2")
        self.username = QtWidgets.QTextEdit(parent=Dialog)
        self.username.setGeometry(QtCore.QRect(150, 110, 221, 31))
        self.username.setObjectName("username")
        self.email = QtWidgets.QTextEdit(parent=Dialog)
        self.email.setGeometry(QtCore.QRect(150, 210, 221, 31))
        self.email.setObjectName("email")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(30, 120, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 170, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 220, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(150, 60, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 0, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.password = QtWidgets.QLineEdit(parent=Dialog)
        self.password.setGeometry(QtCore.QRect(150, 160, 221, 31))
        self.password.setObjectName("password")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.login.setText(_translate("Dialog", "Đăng nhập"))
        self.register_2.setText(_translate("Dialog", "Đăng ký"))
        self.label.setText(_translate("Dialog", "Tên đăng nhập"))
        self.label_2.setText(_translate("Dialog", "Mật khẩu"))
        self.label_3.setText(_translate("Dialog", "Email"))
        self.label_4.setText(_translate("Dialog", "ĐĂNG KÝ"))
        self.label_5.setText(_translate("Dialog", "QUẢN LÝ CỬA HÀNG ĐIỆN THOẠI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
