# Form implementation generated from reading ui file 'tab.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(333, 443)
        self.btnhome = QtWidgets.QPushButton(parent=Dialog)
        self.btnhome.setGeometry(QtCore.QRect(0, 90, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btnhome.setFont(font)
        self.btnhome.setObjectName("btnhome")
        self.btnhd = QtWidgets.QPushButton(parent=Dialog)
        self.btnhd.setGeometry(QtCore.QRect(0, 140, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btnhd.setFont(font)
        self.btnhd.setObjectName("btnhd")
        self.btnsp = QtWidgets.QPushButton(parent=Dialog)
        self.btnsp.setGeometry(QtCore.QRect(0, 190, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btnsp.setFont(font)
        self.btnsp.setObjectName("btnsp")
        self.btnkh = QtWidgets.QPushButton(parent=Dialog)
        self.btnkh.setGeometry(QtCore.QRect(0, 240, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btnkh.setFont(font)
        self.btnkh.setObjectName("btnkh")
        self.btnkm = QtWidgets.QPushButton(parent=Dialog)
        self.btnkm.setGeometry(QtCore.QRect(0, 290, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btnkm.setFont(font)
        self.btnkm.setObjectName("btnkm")
        self.btnls = QtWidgets.QPushButton(parent=Dialog)
        self.btnls.setGeometry(QtCore.QRect(0, 340, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btnls.setFont(font)
        self.btnls.setObjectName("btnls")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(30, 10, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btndx = QtWidgets.QPushButton(parent=Dialog)
        self.btndx.setGeometry(QtCore.QRect(0, 390, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btndx.setFont(font)
        self.btndx.setObjectName("btndx")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnhome.setText(_translate("Dialog", "Home"))
        self.btnhd.setText(_translate("Dialog", "Hoá đơn"))
        self.btnsp.setText(_translate("Dialog", "Sản phẩm"))
        self.btnkh.setText(_translate("Dialog", "Khách hàng"))
        self.btnkm.setText(_translate("Dialog", "Khuyến mãi"))
        self.btnls.setText(_translate("Dialog", "Lịch sử"))
        self.label.setText(_translate("Dialog", "CỬA HÀNG BÁN ĐIỆN THOẠI"))
        self.btndx.setText(_translate("Dialog", "Đăng xuất"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
